# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src
COPY ["OdeToFood.csproj", "."]
COPY ["OdeToFood.Data/OdeToFood.Data.csproj", "OdeToFood.Data/"]
COPY ["OdeToFood.Core/OdeToFood.Core.csproj", "OdeToFood.Core/"]
RUN dotnet restore "./OdeToFood.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./OdeToFood.csproj" -c Release -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish

RUN dotnet publish "./OdeToFood.csproj" -c Release -o /app/publish 

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OdeToFood.dll"]